scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile9`, function (sprite, location) {
    info.changeScoreBy(1)
})
info.onScore(1, function () {
    tiles.setCurrentTilemap(tilemap`level1`)
})
info.startCountdown(10)
tiles.setCurrentTilemap(tilemap`level4`)
let mySprite = sprites.create(img`
    . . 6 6 6 6 . . 
    . 6 d 4 4 4 6 . 
    6 1 b 1 1 4 d 6 
    c 1 b b 4 4 1 c 
    . c b b b d c . 
    . . c c c c . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
animation.runImageAnimation(
mySprite,
[img`
    ..6666..................
    .6d4446.................
    61b114d6................
    c1bb441c................
    .cbbbdc.................
    ..cccc..................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `],
500,
true
)
